// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiIFQqd6sifrR-DcWefU2E0fWiNCI3G1A',
    appId: '1:412678793983:web:17c41ffd09c9b451cbbaca',
    messagingSenderId: '412678793983',
    projectId: 'capsnap-18dbf',
    authDomain: 'capsnap-18dbf.firebaseapp.com',
    databaseURL: 'https://capsnap-18dbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capsnap-18dbf.firebasestorage.app',
    measurementId: 'G-3E3292M7WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZojKAUL128fpPpKBUOmJIaM6SPggCgJQ',
    appId: '1:412678793983:android:1811fe856a4fbf3bcbbaca',
    messagingSenderId: '412678793983',
    projectId: 'capsnap-18dbf',
    databaseURL: 'https://capsnap-18dbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capsnap-18dbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFXTOL9QfL9OzowxevcYQMdpmKRzrqbb4',
    appId: '1:412678793983:ios:9ba3c30cd4e6a28dcbbaca',
    messagingSenderId: '412678793983',
    projectId: 'capsnap-18dbf',
    databaseURL: 'https://capsnap-18dbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capsnap-18dbf.firebasestorage.app',
    iosBundleId: 'com.example.esp32BleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFXTOL9QfL9OzowxevcYQMdpmKRzrqbb4',
    appId: '1:412678793983:ios:9ba3c30cd4e6a28dcbbaca',
    messagingSenderId: '412678793983',
    projectId: 'capsnap-18dbf',
    databaseURL: 'https://capsnap-18dbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capsnap-18dbf.firebasestorage.app',
    iosBundleId: 'com.example.esp32BleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiIFQqd6sifrR-DcWefU2E0fWiNCI3G1A',
    appId: '1:412678793983:web:8461f36a78067759cbbaca',
    messagingSenderId: '412678793983',
    projectId: 'capsnap-18dbf',
    authDomain: 'capsnap-18dbf.firebaseapp.com',
    databaseURL: 'https://capsnap-18dbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capsnap-18dbf.firebasestorage.app',
    measurementId: 'G-GE0K4L75BD',
  );

}